### ISSUE TITLE
Missing dependencies ?

### ISSUE THREAD

**Issue by atiro** [mhbeals/nisaba#27]
Hi, was interested to try the code but am getting the following errors after pip install in a fresh virtualenv (Python 3.8)

Traceback (most recent call last):
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/__main__.py", line 4, in <module>
    from database_display import *
ModuleNotFoundError: No module named 'database_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/database_display.py", line 3, in <module>
    from database_maintenance import *
ModuleNotFoundError: No module named 'database_maintenance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/taxonomy_display.py", line 3, in <module>
    from database_display import *
ModuleNotFoundError: No module named 'database_display'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/richard/.virtualenvs/nisaba/bin/nisaba", line 5, in <module>
    from nisaba.__main__ import main
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/__main__.py", line 11, in <module>
    from nisaba.database_display import *
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/database_display.py", line 9, in <module>
    from nisaba.taxonomy_display import *
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/taxonomy_display.py", line 11, in <module>
    from nisaba.database_maintenance import *
  File "/home/richard/.virtualenvs/nisaba/lib/python3.8/site-packages/nisaba/database_maintenance.py", line 10, in <module>
    from tkinter import END
ModuleNotFoundError: No module named 'tkinter'

**Comment by mhbeals** [comment]
@atiro Pip Install has been updated this week. Could you try again and let me know if the missing dependency issue remains? It seems to work outside virtual environments so I want to narrow the variables before I begin pursuing a definite fix. Many thanks for your interest!
