### ISSUE TITLE
Reference Image no longer working

### ISSUE THREAD

**Issue by mhbeals** [mhbeals/nisaba#29]
Traceback (most recent call last):
  File "c:\users\mhb\appdata\local\programs\python\python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "c:\users\mhb\appdata\local\programs\python\python38\lib\site-packages\nisaba\database_display.py", line 1153, in <lambda>
    self.reference_image_rotate_button = Button(self.item_tab_four, image=self.refresh_icon,command=lambda:reference_image_rotater(self.reference_imageCanvas))
AttributeError: 'database_display' object has no attribute 'reference_imageCanvas'

**Comment by mhbeals** [comment]
Fixed in 0.3.9
